# Generated by Django 2.2.5 on 2021-04-26 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_url', models.CharField(max_length=10)),
                ('original_url', models.CharField(max_length=500)),
                ('frequency', models.IntegerField(default=0)),
            ],
        ),
    ]
