# Generated by Django 2.2.5 on 2021-05-25 14:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortUrls', '0002_auto_20210520_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 25, 17, 50, 9, 964315)),
        ),
    ]
