# Generated by Django 2.2.5 on 2021-05-25 14:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shortUrls', '0003_url_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 25, 14, 58, 32, 693273, tzinfo=utc)),
        ),
    ]
