# Generated by Django 2.2.5 on 2021-05-26 14:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shortUrls', '0004_auto_20210525_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 26, 14, 43, 25, 270662, tzinfo=utc)),
        ),
    ]
