# Generated by Django 2.2.5 on 2021-05-26 16:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shortUrls', '0007_auto_20210526_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 26, 16, 2, 18, 700862, tzinfo=utc)),
        ),
    ]
