// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;

namespace Autotests
{
    [TestFixture]
    public class FourthTest : TestBase
    {
        [Test]
        public void fourthTest()
        {
            //app.Navigation.OpenHomePage();
            //app.Windows.GetWindowsSize();
            //app.Login.Login(user);
            app.Note.DeleteNote();
            var isDel = app.Note.IsDeleted();
            Assert.AreEqual(true, isDel);
        }
    }
}

