// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
using System.Xml.Serialization;
using System.IO;

namespace Autotests
{
    [TestFixture]
    public class SecondTest : TestBase
    {
        public static IEnumerable<Node> NotesFromXmlFile()
        {
            return (List<Node>)new XmlSerializer(typeof(List<Node>))
                .Deserialize(new StreamReader(@"C:\Users\Dimon\source\repos\Autotests\AddressBookTestDataGenerators\bin\Release\netcoreapp3.1\notes.xml"));
        }


        [Test, TestCaseSource("NotesFromXmlFile")]
        public void secondTest(Node node)
        {
            app.Navigation.OpenHomePage();
            app.Windows.GetWindowsSize();
            app.Login.Login(user);
            app.Note.CreateNote(node);
            var createdNode = app.Note.GetNote();
            Assert.AreEqual(true, createdNode);
        }
    }
}

